services:
  proxy:
    build: .
    command:
      - '--verbose'
    networks:
      - nakoud
    ports:
      - '127.0.0.1:8080:8080/tcp'
      - '[::1]:8080:8080/tcp'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:z'

networks:
  nakoud:
    name: nakoud
