name: go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'

      - uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.52.2'

      - name: Build
        run: go build ./...
