name: go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.3'

      - uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.52.2'
          skip-pkg-cache: true

      - name: Build
        run: make build

      - uses: actions/upload-artifact@v3
        with:
          name: nakoud-proxy
          path: ./bin/nakoud-proxy
